use crate::config::Config;
use global_hotkey::{
    hotkey::{Code, HotKey, Modifiers},
    GlobalHotKeyManager, HotKeyState,
};
use std::{collections::HashMap, error::Error};

/// Represents the mapping from a registered hotkey ID to the target device name.
pub type HotkeyDeviceMap = HashMap<u32, String>;

/// Registers hotkeys defined in the configuration.
///
/// Takes the application configuration and initializes the global hotkey manager,
/// registering each hotkey specified in the config.
///
/// Returns a tuple containing the initialized `GlobalHotKeyManager` and a
/// `HotkeyDeviceMap` mapping the registered hotkey IDs to their corresponding
/// device names.
pub fn register_hotkeys(config: &Config) -> Result<(GlobalHotKeyManager, HotkeyDeviceMap), Box<dyn Error>> {
    let manager = GlobalHotKeyManager::new()?;
    let mut hotkey_device_map: HotkeyDeviceMap = HashMap::new();

    println!("Registering hotkeys..."); // Debugging output

    for mapping in &config.hotkeys {
        // The Modifiers and Code are already parsed in the Config struct
        let hotkey = HotKey::new(Some(mapping.modifiers), mapping.key);
        let id = hotkey.id(); // Get the unique ID generated by the HotKey struct

        println!(
            "  Registering: Modifiers={:?}, Key={:?}, ID={}, Device='{}'",
            mapping.modifiers, mapping.key, id, mapping.device_name
        ); // More detailed debug

        manager.register(hotkey)?;

        // Store the mapping from the hotkey's ID to the device name
        hotkey_device_map.insert(id, mapping.device_name.clone());
    }

    if hotkey_device_map.is_empty() {
        println!("Warning: No hotkeys found in the configuration to register.");
    } else {
        println!("Successfully registered {} hotkeys.", hotkey_device_map.len());
    }


    Ok((manager, hotkey_device_map))
}

// Optional: Add a function to handle cleanup if needed, though the manager might handle it on drop.
// pub fn unregister_hotkeys(manager: &GlobalHotKeyManager, hotkeys: &[HotKey]) -> Result<(), Box<dyn Error>> {
//     println!("Unregistering hotkeys...");
//     for hotkey in hotkeys {
//         manager.unregister(*hotkey)?;
//     }
//     println!("Hotkeys unregistered.");
//     Ok(())
// }